### ISSUE TITLE
Window warnings & legend error

### ISSUE THREAD

**Issue by eckertf** [mbannert/tstools#11]
library(tstools)

# data
ts1 <- ts(runif(100,0,1), start = 1990, frequency = 4)
ts2 <- ts(runif(100,90,110), start = 1990, frequency = 4)
tslist_plot <- list(ts1,ts2)

# theme (for window)
tt <- initDefaultTheme()
tt$highlight_window <- T
tt$highlight_window_end <- c(2015,1)
tt$highlight_window_start <- c(2012,1)

tsplot(tslist_plot[1],
       tsr=tslist_plot[2],
       left_as_bar = T,
       theme = tt,
       plot_title = paste("Consumer Price Inflation"),
       manual_value_ticks_l = seq(-3,4.5, by=1.5),
       manual_value_ticks_r = seq(92,112, by=4),
       plot_subtitle = "(in %)",
       plot_subtitle_r = paste0("Index (", horizon-5, " = 100)"))

**Comment by HomoCodens** [comment]
@eckertf Can you elaborate on what warning you got? It this still relevant?

This does not cause any issues for me:
```
ts1 <- ts(runif(100,0,1), start = 1990, frequency = 4)
ts2 <- ts(runif(100,90,110), start = 1990, frequency = 4)
tslist_plot <- list(ts1,ts2)

tt <- initDefaultTheme()
tt$highlight_window <- T
tt$highlight_window_end <- c(2015,1)
tt$highlight_window_start <- c(2012,1)

tsplot(tslist_plot[1],
       tsr=tslist_plot[2],
       left_as_bar = T,
       theme = tt,
       plot_title = paste("Consumer Price Inflation"),
       manual_value_ticks_l = seq(-3,4.5, by=1.5),
       manual_value_ticks_r = seq(92,112, by=4),
       plot_subtitle = "(in %)",
       plot_subtitle_r = "right subtitle")
```

**Comment by eckertf** [comment]
This works now perfectly fine, thank you!
