### ISSUE TITLE
Margin for legend is always reserved - even if auto legend is false

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#111]
```
library(tstools)

data("CHGDP")
tsplot(CHGDP,left_as_bar = T,auto_legend = F)

```

![rplot 1](https://user-images.githubusercontent.com/1382079/37119393-8c5ca298-2257-11e8-81d5-8d8b69f6eee4.png)
I just write some gibberish here to show how big that margin actually is.
Not sure how to fix this properly. Cause if we just remove that additional margin in case of auto_legend = F, it'll prevent users from adding their own custom made legends. Yet, I believe removing it should be the default behavior. Probably we need another parameter like force_keep_legend_margin which is only in effect if auto_legend = F.

**Comment by HomoCodens** [comment]
Added two parameters to control this. The margin now behaves according to the table below. Parentheses mean the parameter gets overridden by earlier ones.

| margins[1]  | auto_legend | auto_bottom_margin | actual margin |
|-------------|-------------|--------------------|---------------|
| NA          | T           | (T)                | auto          |
| NA          | T           | (F)                | auto          |
| NA          | F           | T                  | auto          |
| NA          | F           | F                  | default       |
| user           | (T)         | (T)                | user             |
| user           | (T)         | (F)                | user             |
| user           | (F)         | (T)                | user             |
| user           | (F)         | (F)                | user             |
