### ISSUE TITLE
Confidence intervals for time series

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#117]
Confidence intervals for time series would be a nice extension. Not sure about the interface yet, but here's one idea: 

- have a vector of logicals for each side tsl_ci and tsr_ci. 
- have ci_interval_threshold param for 95% 99% 80% etc. 
- ci band color
- ci band alpha

overlap might be a challenge.

**Comment by HomoCodens** [comment]
Do you have an example of what this might look like?

How are these confidence intervals calculated?

**Comment by mbannert** [comment]
This isn't fully mapped out. I am not sure whether we should help compute it or simply create a possibility to draw polygons around lines, pretty similar to highlight windows but a little more tricky to shape :) I'll put a little more thought into this.

**Comment by mbannert** [comment]
code wise we could get inspirations from Rob Hyndman's forecasting package: 
https://robjhyndman.com/hyndsight/forecast-intervals-for-aggregates/

Since I do not want to do forecast within tstools, the idea should be rather to specify upper and lower bound and plot those.

**Comment by HomoCodens** [comment]
Do we want confidence interval support for both left and right axis?

**Comment by HomoCodens** [comment]
I can't get over the desire to allow for arbitrary confidence levels but that would require a parameter that is three levels deep:

```R
ci <- list(
    series1 = list(
        85 = list(
            ub = ts,
            lb = ts
        ),
        "93.1415926" = list(
             ub = ts,
             lb = ts
        )
     ),
    series2 = list(
```
and so on.

Is this overengineering the issue?
Do we need to support bands for multiple series or is this only ever going to be uses with single series plots? Too many bands would be confusing anyway I believe.

**Comment by HomoCodens** [comment]
Making good progress (see branch `iss_117`)

```R
y <- sin(seq(0, 13, 0.1))

tslist <- list(sin = ts(y, start = 1988, frequency = 12))

forecasted_values <- window(tslist$sin, start = 1997.5)
deviation_85 <- 0.4*(0.8^(length(forecasted_values):1))
lb_85 <- forecasted_values - deviation_85
ub_85 <- forecasted_values + deviation_85

deviation_99 <- 1.2*(0.8^(length(forecasted_values):1))
lb_99 <- forecasted_values - deviation_99
ub_99 <- forecasted_values + deviation_99

ci <- list(
  sin = list(
    "85" = list(
      ub = ub_85,
      lb = lb_85
    ),
    "99" = list(
      ub = ub_99,
      lb = lb_99
    )
  )
)

tsplot(tslist, ci = ci, theme = init_tsplot_theme(line_colors = "red"))
```

![a sine](https://user-images.githubusercontent.com/32675029/40613457-1ae3097a-626e-11e8-8d04-b0c821e4836c.png)

Just noticed the legend colors are backwards... Back to it!
