### ISSUE TITLE
multiple highlight windows

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#118]
our highlight window was introduced to highlight forecast horizon, which you usually have at the end of your data period. But it would also be nice to be able to highlight multiple parts of a time series. 

Maybe a time series with logicals would be a good solution.

**Comment by HomoCodens** [comment]
A logical time series sounds cumbersome to construct. How about something along these lines:

```R
library(tstools)

tsb1 <- ts(runif(30,0,abs(runif(1, 0, 50))),start=c(2008,1),frequency = 4)
tsb2 <- ts(runif(30,0,abs(runif(1, 0, 50))),start=c(2010,1),frequency = 4)

tt <- init_tsplot_theme(highlight_window = TRUE, highlight_window_start = list(c(2011, 1), c(2014, 1)), highlight_window_end = list(c(2012, 4), c(2015, 4)))

tsplot(tsb1, tsb2, theme = tt, left_as_bar = TRUE, group_bar_chart = FALSE)
```

Alternatively
```R
highlight_windows = list(list(start = c(2011, 1), end = c(2012, 4)), list(start = c(2014, 1), end = c(2015, 4)))
```
This semantically groups the windows but
1) Is more complicated to construct?
2) Breaks backwards compatibility.

**Comment by mbannert** [comment]
Ok, I am sold that this is better than logicals.
I like the first solution, though the alternative is a bit more intuitive, but breaking backwards compatibility is a strong counter argument to me. If a look at the graphs out there that use tstools, plenty of them use highlight window...
