### ISSUE TITLE
write_ts doesn't work with yearly data

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#119]
```
write_ts(ts(rnorm(10),start=1990),date_format = "%Y")

```

causes the following data.table error:
```
Error in `[.data.table`(tsdf, , `:=`(freq = frequency(tl[[index]]), series = tl_names[index],  : 
  RHS is NULL when grouping :=. Makes no sense to delete a column by group. Perhaps use an empty vector instead.
```

**Comment by HomoCodens** [comment]
Not an issue with yearly data but rather that `write_ts` expects a _named list_ of time series.

```R
write_ts(list("ts1" = ts(rnorm(10),start=1990)),date_format = "%Y")
```

We could expand it to also take other inputs (similar to `tsplot`) and/or think about providing default names if an unnamed list is passed:

This will cause the same error.
```R
write_ts(list(ts(rnorm(10),start=1990)),date_format = "%Y")
```

**Comment by HomoCodens** [comment]
Exporting data with arbitrary names seems to be of limited use though.
