### ISSUE TITLE
Horizontal Tick marks

### ISSUE THREAD

**Issue by eckertf** [mbannert/tstools#12]
Yearly-tick marks could be a bit longer, it is difficult to differentiate the yearly and quarterly tick marks for larger figures. They don't have to be as long as in the SECO figures (see attached file for example), but just a bit.
![figure](https://user-images.githubusercontent.com/30232467/30317292-fe2804dc-97a9-11e7-8393-f94819a78c6a.jpeg)

**Comment by mbannert** [comment]
maybe we need to add a tick length parameter. let's check whether that is possible

**Comment by HomoCodens** [comment]
See issue branch.

Sample usage:
```R
library(tstools)

tsb1 <- ts(runif(30,0,abs(runif(1, 0, 50))),start=c(2010,1),frequency = 4)
tsb2 <- ts(runif(30,0,abs(runif(1, 0, 80))),start=c(2010,1),frequency = 4)

tt <- init_tsplot_theme(tck_yearly_ticks = -0.08, tck_quarterly_ticks = -0.02)

tsplot(tsb1, tsb2, left_as_bar = TRUE, theme = tt)
```

**Comment by HomoCodens** [comment]
PR merged into dev. Closing.
