### ISSUE TITLE
Option to store plots in file

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#121]
Something along those lines would work:

```R
library(tstools)

tsb1 <- ts(runif(30,0,abs(runif(1, 0, 50))),start=c(2010,1),frequency = 4)
tsb2 <- ts(runif(30,0,abs(runif(1, 0, 80))),start=c(2010,1),frequency = 4)

tt <- init_tsplot_theme()

pdf("pla.pdf", 8, 6)
tsplot(tsb1, tsb2, theme = tt, left_as_bar = TRUE) #, group_bar_chart = TRUE)
dev.off()
``` 

Where the graphics device calls surrounding `tsplot` would be inside the function itself.

**Comment by HomoCodens** [comment]
Made some forays into this issue by adding a `output_format` parameter and related ones to `tsplot`.

See 50ac86b

The question arises again whether these parameters should be theme- or tsplot-parameters. I feel they don't have much to do with the "theming" of the plot.

**Comment by mbannert** [comment]
not so sure about these params not being related to theming. In general I think this one of the more important issues. I have something like a print theme in mind  😄 .... I want to avoid people screen shooting out of a knitted .pdf or opening .pdf in indesign to change size of fonts and labels...

**Comment by HomoCodens** [comment]
To me the word "theme" implies that the parameters are to do with what the plot *looks* like (e.g. colours, font sizes etc.) whereas whether it is shown in an R plot or stored in an image does not change these looks.

**Comment by HomoCodens** [comment]
If it's only about canvas dimensions the same can be achieved by providing sensible defaults for the `tsplot` parameters. :wink:

Although I did notice that the line thickness is off when plotting to a 4x3 inch pdf (which seems like an adequate size for a simple plot figure. Making it 8x6 just so it looks good makes  no sense.).

[tsplot.pdf](https://github.com/mbannert/tstools/files/1897676/tsplot.pdf)

Also, the dimensions are specified in pixels for the image formats and only in inches for pdf. Inches are also possible for images but then a ppi resolution must also be provided.

Maybe we can try massaging the default theme until it looks good for some standard size pdf and look where that takes us.

**Comment by mbannert** [comment]
"Although I did notice that the line thickness is off when plotting to a 4x3 inch pdf (which seems like an adequate size for a simple plot figure. Making it 8x6 just so it looks good makes no sense.)."

Exactly. This is the behavior I am talking about. I doubt that there are reasonable defaults that suit interactive, on screen use as well as .pdf export type of use cases. Hence I thought a print theme would be a good idea. I think this would also help to turn some of these outputs to tstools outputs:

https://www.kof.ethz.ch/news-und-veranstaltungen/medien/medienmitteilungen/2018/03/kof-konjunkturbarometer-faellt.html

**Comment by HomoCodens** [comment]
I'm leaning more and more towards an auto scaling method.
1) Producing an identical looking plot twice the size should just be a matter of changing the dimensions, not fiddling with other parameters
2) We wouldn't necessarily need a separate theme for file output. The relevant parameters could just be scaled by the height

Also the automatic calculation of the bottom margin to fit the legends is causing trouble. Will have to look into that.
