### ISSUE TITLE
Multiline Subtitles

### ISSUE THREAD

**Issue by dude233** [mbannert/tstools#137]
```
library(tstools)
test <- list(ts(rnorm(20), start=1989))
tsplot(test,
       plot_title="This is a Test",
       plot_subtitle="We wish to have \nmulti-line Subtitles")
```

```
tsplot(test,
       plot_title="This is a Test \nmulti-line Title",
       plot_subtitle="This one works")
```
See that multi-line subtitles do not work, main multi-line titles do, however.

**Comment by HomoCodens** [comment]
@dude233 
How about something like this:
```R
library(tstools)
test <- list(ts(rnorm(20), start=1989))
tsplot(test,
       plot_title="This is a Test",
       plot_subtitle="We wish to have \nmulti-line Subtitles",
       theme = init_tsplot_theme(margins = c(NA, 4.1, 4.1, 3.1), title_line = 2.8))
```

![rplot](https://user-images.githubusercontent.com/32675029/38854612-9218dd72-4210-11e8-8251-357c54fe8c6f.png)

Here I adjusted the top margin (`margins[3]`) and `title_line`.

Alternatively we'd probably need to autocalculate `title_line` and the top margin like we do with the bottom margin.

**Comment by HomoCodens** [comment]
The manual version is OK for now.

Should the need arise, we can have a look at automatically determining the values later.
