### ISSUE TITLE
Systematic NAs are not handled well in plots

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#138]
When mixing quarterly and monthly data in one time series object, data are sometimes extrapolated to higher frequency like this: 

```
library(tstools)
xx <- rnorm(100)
xx[!c(T,F,F)] <- NA
yy <- c(xx,rnorm(20))
tsy <- ts(yy,start = c(1998,1),frequency = 12)
```
> tsy
             Jan         Feb         Mar         Apr         May         Jun         Jul         Aug         Sep         Oct         Nov
1998  0.07056418          NA          NA -0.05046880          NA          NA  1.18340653          NA          NA  0.11842352          NA
1999  1.36871572          NA          NA -0.17948716          NA          NA  1.30193342          NA          NA -0.06729021          NA
2000 -1.75094578          NA          NA -0.07142272          NA          NA  1.64899741          NA          NA  0.13143400          NA
2001  2.27216878          NA          NA  0.79059318          NA          NA  0.68073382          NA          NA -1.35827744          NA
2002  0.21417265          NA          NA -0.15489709          NA          NA -1.92354391          NA          NA -1.24127590          NA
2003 -0.57599268          NA          NA  0.63164726          NA          NA  0.19473970          NA          NA  0.57109892          NA
2004 -0.15732346          NA          NA -1.11519473          NA          NA  0.87780149          NA          NA -0.07427103          NA
2005 -0.71304424          NA          NA  0.21661621          NA          NA -0.87542017          NA          NA -0.45473464          NA
2006 -0.08510466          NA          NA -0.50195691  0.69912863  1.13156310 -0.09982897  1.00651774 -1.72344085  0.37457057  0.92408102
2007 -0.52084434 -2.19145461  0.12044779 -1.75996123 -1.00271701  0.80620400  1.91946676  0.85876965 -1.31655150  1.56400123  0.44732574

Which results in a `tsplot` which ignores the quarterly part /w NAs. 
![rplot](https://user-images.githubusercontent.com/1382079/38742337-8e174780-3f3c-11e8-96af-d9b8c49ae3ed.png)

However, `tstools` provides the `m_to_q` function which turns monthly series with any sort of interpolation to quarterly series.  

```
tsx <- ts(xx,start = c(1990,1),frequency = 12)
tsplot(m_to_q(tsx))


```

![rplot01](https://user-images.githubusercontent.com/1382079/38742488-fa87ca5c-3f3c-11e8-9aba-dc96f22be72f.png)

@dude233 is this what you were talking about? 

I think there is no other solution but splitting the series and redrawing the plot. Just wonder whether tsplot or the user needs to split the series in two?

**Comment by HomoCodens** [comment]
How would we wish to draw the part with missing values?

1) As a continuous line with lower frequency?
2) As a broken up line with nothing where data is missing (pro: this is probably the best way to draw a series with data missing at irregular intervals. con: only a single point would be drawn for each value in the example above)?
3) Choice between 1. and 2.?

I'm going to have a look into what causes this behaviour.

**Comment by HomoCodens** [comment]
OK looks like `lines` behaves as expected:
```
The coordinates can contain NA values. If a point contains NA in either its x or y value, it is omitted from the plot, and lines are not drawn to or from such points. Thus missing values can be used to achieve breaks in lines.
```

The points are there but no lines are drawn since only one "neighboring non-NA point" is specified in the series.

```R
plot(NULL,
     xlim = c(-3, 3),
     ylim = c(-1, 1))
lines(x = -3:3, y = c(-1, -1, NA, 0, NA, 1, 1))
```
![rplot](https://user-images.githubusercontent.com/32675029/38856752-d55598ea-4216-11e8-82ee-65a4011310e4.png)

We should:
1) Add `type` and `pch` parameters to `theme`

We *could*:
1) Add the option to linearly interpolate data for missing points to get the lines to draw (see option 1. in the comment above)
2) Split and properly draw the series

Making the user worry about overplotting series with missing values does not seem like a good idea.

**Comment by mbannert** [comment]
You nailed it. This is exactly the problem. The case were you have 'regular' NAs in off quarter months and normal monthly series later on seems kinda KOF specific. Given that R usually connects single points in time when plotting time series makes users (who don't care frequency) want to have that very same behavior, too. 

On the other hand. It's a good thing that R distinguishes between a value that's not even there and a value that is not available but shoulda been measured (NA). Thus for latter there's an invisible dot, for the former there's not. It doesn't seem overly smart to me to throw this distinction under the bus. 

EDIT: I see you're quicker than me here 👍 . Maybe a general thing: I like lots of defaults and parameters for tsplot, but I think it should still be **separation of concerns**. Plotting should not do too much.  

Personally I like your plot with the dots a lot, cause it immediately show what's happening. But I am almost sure our users won't like it 😄 . However, a `pch` option for theme would be nice in any case!! 

ad options: 
- repeating values introduces steps and should not be the default behavior even if some people do it all the time. 
- linear interpolation would introduce values which are not there... as long as we do not show dots, it should be fine though. But how would we distinguish a single interior `NA` from a set of regular ones?
- maybe splitting would be the 👑 -solution. But it would require to introduce something like a group of series in order to have the same legend and color.... 

should we move this to 0.3.7 ?

**Comment by HomoCodens** [comment]
Yes if we add a dots option then interpolated values would also get points which would not be desirable.

I think if we just split the series in `draw_ts_lines` and call `lines` several times we won't get any problems with legends etc.
If we want to be a general purpose time series plotting tool I think we should aim for a generally applicable solution that also handles non-KOF-specific NA values though.

This would do the trick but again eliminate emphasizing missing values with gaps in the line so it should be an option at most, not the default:

```R
draw_ts_lines.list <- function(x, theme = NULL){
  for (i in 1:length(x)){
    xx <- as.numeric(time(x[[i]]))
    yy <- x[[i]]
    frq <- frequency(x[[i]])
    
    if(theme$line_to_middle){
      xx <- xx+(1/frq)/2
    }
    
    yy_na <- is.na(yy)
    yy <- yy[!yy_na]
    xx <- xx[!yy_na]
    
    lines(xx,yy,
          col = theme$line_colors[[i]],
          lwd = ifelse(length(theme$lwd) > 1,
                       theme$lwd[i],
                       theme$lwd),
          lty = ifelse(length(theme$lty) > 1,
                       theme$lty[i],
                       theme$lty)
    )
  }
  
}
```

Specifically
```R
    yy_na <- is.na(yy)
    yy <- yy[!yy_na]
    xx <- xx[!yy_na]
```

![rplot02](https://user-images.githubusercontent.com/32675029/38859338-52151698-421d-11e8-8633-6fc9bfc2468f.png)

**Comment by mbannert** [comment]
Ok. This seems really nice. Let me see if I got this correctly:
- the input is a monthly ts which starts off with several regular `NAs` then it turns into a monthly series without `NAs`. By splitting it we see a nice plot without 'artificial', interpolated values as shown by the dots. 

- still we have only one legend and the same color

So what would this do to some random, interior NA?
Also, this would imply regular frequency to work. We would need to document this, but that doesn't mean that this is a good solution. Just challenging it a bit to not only help the KOF specific case of mixing frequencies the way we do...

**Comment by mbannert** [comment]
No doubt here. What you call *without* is the desired plot. I had the *with* to the point that I am not sure that I want to provide that, but maybe adding an option is the more diplomatic approach if it comes at low costs. Clearly, without should be the default.

**Comment by HomoCodens** [comment]
Yes, the only case where *with* is a reasonable option is the somewhat KOF-specific frequency switch within a time series.

We can now 
1) Decide these need to be shown with the new points parameters or the user needs to remove undesired `NA`s before plotting
2) Add an `ignore_NAs` theme parameter with default FALSE
