### ISSUE TITLE
completely manual x-axis

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#151]
I learned about this feature request from a non-GH user. Hence I'll post it on behalf of him. 
Is there a way to have irregular axis ticks? Like, ticks at 1996,1999,2002,2005 or so?
Maybe we already have this someone, maybe this in entirely impossible. 
I think this should be possible – at least if those irregular ticks are within the range of the series...

**Comment by HomoCodens** [comment]
There are two issues here:
1) Specify axis ticks completely manually (e.g. 1990, 1991, 2000, 2001, 2003, 2100)
2) Have regular ticks at intervals > 1 year (what your example suggests)

At a glance both should be doable by modifying `getGlobalXInfo` which generates all x axis info.

The highlight window could cause undesired behaviour (`xl <- global_x$x_range[2]-2`).
