### ISSUE TITLE
speed issue with writeTimeSeries

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#16]
@HomoCodens tried to export a large a amount of series for partner. Waaayyyy more data then exported before. Thought I/O was slow, but I was wrong. Problem are R conversion. Ran some profiling on `writeTimeSeries` and learned `do.call() + rbind` is slow. Also `lapply(tl, as.xts)` is not exactly fast, but seems necessary. 

here's a first take at speeding up things make use of data.table's C speed.

```
# o is just a list of 10K ts objects
o <- out[1:10000]
ox <- lapply(o,as.xts)
odt <- lapply(names(ox),function(x){
  data.table(date = as.Date(index(ox[[x]])),
             value = ox[[x]],
             keys = x)
})

oxl <- rbindlist(odt)
```
building odt costs a little, so does lapply with xts, but it's ok. Guess this + fallback for no data.table already helps a lot.

**Comment by mbannert** [comment]
Once we figured out the speed problem we ran into memory issues. I think ripping all lists apart to vectors and put those into large data.table is the easies solution. Tested stuff like this 25M+ records and it performed really really well (1-2 min). fwrite is easy then. Need optimize the name stuff a bit an verify a bit. 

```
dt <- data.table(date = unlist(lapply(inu1,index)),
           value = unlist(inu1))
```
What do you think?

**Comment by mbannert** [comment]
@HomoCodens: 
we're getting there but, long lists are still too slow. according to the profile right here: 
![image](https://user-images.githubusercontent.com/1382079/35095517-01180f62-fc49-11e7-9c16-67a3bafb6184.png)

as.character conversion takes a lot of time. 
also not sure whether data.table is faster than data.frame. If not we need to remove the data_available clause (but that's another issue technically). Maybe chunking helps, problem does not seem to be linear.

**Comment by HomoCodens** [comment]
How many series are you using for those tests?
Any quick snipped to get a similar set?

**Comment by HomoCodens** [comment]
100'000 series in 88 seconds. How about that? :sunglasses:
Confident there's a way to get that down another 70-80% or so (line 75). 

![writetimeseries_speedup](https://user-images.githubusercontent.com/32675029/35162114-8c1a9220-fd42-11e7-80ac-7eb99fdc6209.jpg)

**Comment by HomoCodens** [comment]
16 seconds (too lazy to stitch up another screenshot)! :heart_eyes:

**Comment by mbannert** [comment]
wow. congrats. pretty damn cool. That's a 225 x time speed-up. 
mission accomplished.

 @HomoCodens:1st_place_medal: 
Looking forward to interview the champion and discuss the victorious code.
