### ISSUE TITLE
tsplot built in windowing?

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#166]
Just a fleeting idea:

How about the option to apply a `window` to all ts being plotted?
When playing around with multi-series-plots being able to quickly change the window by setting one parameter would be much more convenient than having to `apply` over the data, storing them in a new variable etc.

**Comment by christophsax** [comment]
tsbox is now on CRAN. It also supports `tslist` (undocumented, but discussed [here](https://github.com/christophsax/tsbox/issues/23)), which is what you use.

Adding to `tsplot.list` the following:

```r
tsl <- tsbox::ts_tslist(ts_c(...))

```

would give you support for all ts-boxable classes for free (e.g. zoo, xts, long data frames). Plus, you can use `ts_span`to window all series as described in this issue.

**Comment by HomoCodens** [comment]
Neat!
We can probably build an "optional dependency" (i.e. use `tsbox::ts_tslist` if `tsbox` is installed) the same way we thought about with `data.table`. Or should we move to a full dependency right now?

wrt to the windowing: On second thought that probably should not be part of the plotting function itself. Maybe add a helper function to apply `window` to a tslist but then again `ts_span` does just that already.
