### ISSUE TITLE
Create S3-class 'cyclingVector' or something

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#167]
Since we have so many parameters that get recycled, an S3 class for vectors that automatically do that comes to mind.

```R
# Fun with S3

'[.recyclableVector' <- function(x, i, j, ..., drop = TRUE) {
  l <- length(x)
  unclass(x)[((i - 1) %% l) + 1]
}

'[<-.recyclableVector' <- function(x, i, j, value) {
  l <- length(x)
  y <- unclass(x)
  y[((i - 1) %% l) + 1] <- value
  class(y) <- class(x)
  y
}

as.recyclable <- function(x) {
  class(x) <- c("recyclableVector", class(x))
  x
}

x <- as.recyclable(1:10)

x[1:12]
x[100]

x[103] <- NA
x
```

Might even be an idea for a separate minipackage.
It's getting into the *super fancy not really necessary at all* territory though. 😛

**Comment by mbannert** [comment]
I like your creativity here :) . I guess there are quite some behavior-changing packages around for everything. Potentially a new programming style 👑 . only briefly looked at it, but found the `x[103] <- NA` a bit weird / unexpected. Explainable in the end... but does it feel comfy?

**Comment by HomoCodens** [comment]
I can only think of a very C-style example but assignments should also wrap with `recyclables`, shouldn't they. Usually this does not happen explicitly as in `x[103]` anyway.
```R
data <- runif(200)
out <- c()
buffer <- recyclable(length = 10, initial_value = 0)
for(i in seq(length(data)) {
  buffer[i] <- data[i]
  out[i] <- mean(buffer)
}
```
With multiple assignments it gets even funkier but it looks like R handles these quite well:
```R
> x <- 1:3
> x
[1] 1 2 3
> x[c(1, 2, 3, 1, 2)] <- 1:5
> x
[1] 4 5 3
```

It'd probably be worth to take a look at how base R does the parameter recycling too.
