### ISSUE TITLE
Misplaced legends in stacked bar & line charts 

### ISSUE THREAD

**Issue by heinermikosch** [mbannert/tstools#173]
When (stacked) bars and lines are joined in one chart, the legends are not properly placed.

[ch_export_contributions.pdf](https://github.com/mbannert/tstools/files/2119706/ch_export_contributions.pdf)

CODE SNIPPET (taken from `vja\international\figures\fig_trade_R`):
```
# Wachstumsbeiträge der Warenexporte und Dienstleistungen sowie Wachstum der EA-Importe und OECD-Importe - Stackedbar/Lineplot
tslist_plot_l <- list("Merchandise Exports (Total 1)" = tslist_national[[paste0("ch.kof.",stand_prognose_schweiz,c(".exc1"))]],
                    "Exports of Services" = tslist_national[[paste0("ch.kof.",stand_prognose_schweiz,c(".exst"))]]) 

tslist_plot_l <- as.list(window(grc(do.call(cbind,tslist_plot_l)),
                                start = settings$horizon-5, end=c(settings$horizon,4)))

tslist_plot_r <- lapply(tslist_international[paste0(c("ea", "oecd"),".kof.",settings$vja_current,".imp")],
                        function(x) window(yoypct(x), start = settings$horizon-5, end=c(settings$horizon,4)))

names(tslist_plot_r) <- c("Euro Area Import Growth (right axis)", "OECD Import Growth (right axis)")

pdf(paste0(path,"ch/ch_export_contributions.pdf"), width=8, height=5)
tsplot(tsl = tslist_plot_l,
       tsr = tslist_plot_r,
       left_as_bar = T,
       auto_legend = T,
       theme = tt_q,
       plot_title = paste0("Swiss Export Growth Contributions and EU/ OECD Import Growth"),
       manual_value_ticks_l = seq(-4.5,4.5, by=1.5),
       manual_value_ticks_r = seq(0,9,by=1.5),
       plot_subtitle = "(in %)")
dev.off()
```

**Comment by HomoCodens** [comment]
I suspect two issues at play here:
1) The theme parameter `legend_col` is set too large, allowing the legends to grow into each other from the left and right sides of the plot

    * Setting `tt_q$legend_col` to 1 should help

2) The legends may be too long. Since the legends for the left and right sides are drawn separately, they must at most be so long that they fill the width of the plot together.

    * Here choosing shorter legends or adding one or two line breaks (`"\n"`) helps.

**Comment by mbannert** [comment]
@heinermikosch this has been fixed on dev. We will deploy this soon on all our servers and also present it together will the other new features. Thanks for your input here. Closed, please reopen if problem persists after release.
