### ISSUE TITLE
Yearly ticks misplaced

### ISSUE THREAD

**Issue by omuelle** [mbannert/tstools#180]
#### To reproduce:

- Load the zipped RData-File: [tsl.zip](https://github.com/mbannert/tstools/files/2166526/tsl.zip)
- Run the following code:
```
th <- init_tsplot_theme()
th$line_colors <- c(rep("black",9), gg_color_hue(9))
th$lwd <- c(rep(2,9), rep(2,9))
th$margins <- c(3,3,1,1)
tsplot(tsl, theme = th, auto_legend = F, manual_value_ticks_l = seq(-4, 6, 2))
```

**Comment by HomoCodens** [comment]
For a quick fix, add `fill_up_start = TRUE` to your call to `tsplot`.

It looks like `getGlobalXInfo` returns garbage (e.g. yearly ticks as yyyy.667) if the ts does not begin at the start of a year.
