### ISSUE TITLE
remove title_outer and subtitle_outer

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#198]
A lot has changed with margins since these were introduced and I don't think placing titles in the outer margins makes sense anymore. Setting `title_outer` to TRUE places the title outside of the visible region (with the other params unchanged. It can be got back by setting `title_line` and `title_adj`) and arbitrary placing is possible with the other parameters anyway.

**Comment by HomoCodens** [comment]
Except placing the title left of the plotting region is not possible as `adj` must be possible. Problem?

**Comment by HomoCodens** [comment]
One way around that would be making `outer` the default.

**Comment by mbannert** [comment]
all good here. no action needed.
