### ISSUE TITLE
auto_legend does not work with confidence intervals

### ISSUE THREAD

**Issue by omuelle** [mbannert/tstools#202]
To reproduce, execute the example code:

```
# load example data
data(KOF)

# Define confidence intervals
ci <- list(
  "KOF Barometer" = list(
    "80" = list(
      lb = KOF$baro_lo_80,
      ub = KOF$baro_hi_80),
    "95" = list(
      lb = KOF$baro_lo_95,
      ub = KOF$baro_hi_95
    )))

tsplot(list("KOF Barometer" = KOF$baro_point_fc),
       ci = ci)
```

The following error results:

> Error in col_r[is_ci_l] <- ci_legend_colors_r : 
  replacement has length zero
Called from: add_legend(names(tsl), names(tsr), ci_names, theme = theme, left_as_bar = left_as_bar)

**Comment by mbannert** [comment]
can't reproduce, please double check.

**Comment by omuelle** [comment]
I still get the same error with the newest dev branch. I built the package on Windows with R 3.5.1.

**Comment by mbannert** [comment]
We just submitted tstools 0.3.7 to CRAN and are waiting for acceptance. Hence we ran tons of checks on different systems including rhub continuous integration tools. 

@homoCodens maybe fresher R versions have problems building it ?

@olmuelle can you try to run your code on one of our rstudios. I just deployed the latest release to all our servers.

**Comment by HomoCodens** [comment]
Can confirm... After updating to `3.5.1` it does not work anymore. That's also what prevented us from passing the CRAN submission.

**Comment by mbannert** [comment]
Admittedly my R is pretty old. But... Wow. R should not break code like that. 

a) do we no what changed ?
b) does only build fail or does the package itself not work anymore after update ?

Can someone check rstudio please (not 2) which is at a least on 3.4.x

**Comment by omuelle** [comment]
I found this in the release notes (3.5.0):

> Subassignment with zero length vectors now coerces as documented (PR#17344).
Further, x <- numeric(); x[1] <- character() now signals an error ‘replacement has length zero’ (or a translation of that) instead of doing nothing.

https://cran.r-project.org/doc/manuals/r-release/NEWS.html

**Comment by HomoCodens** [comment]
Yep I think this is pretty certainly related to that.

Haven't figured out the exact cause between 3.4.4 and 3.5.1 yet, maybe something was just elevated to an error?

Anyway, the good news is that the bug is caused by a simple typo in `add_legend`. The one I noticed earlier in fact.

See #209

**Comment by HomoCodens** [comment]
What we have is basically the following in `add_legend`:

In R 3.4.4
```R
> a <- numeric()
> b <- c()
> a[c(F, T, T)] <- b
> a
numeric(0)
```


In R 3.5.1
```R
> a <- numeric()
> b <- c()
> a[c(F, T, T)] <- b
Fehler in a[c(F, T, T)] <- b : Ersetzung hat Länge 0
> a
numeric(0)
```

Without the typo we get 
```
> a[logical(0)] <- b
```

which works a-ok.
