### ISSUE TITLE
Legend columns should be as wide as the corresponding legend text

### ISSUE THREAD

**Issue by omuelle** [mbannert/tstools#210]
Here the legend doesn't fit, because all columns are as wide as the longest legend text. It doesn't very look good either:

```
tsl <- tstools::generate_random_ts(6, ts_names = c("a","b","this is such a very long text","d","e","f"))
tsplot(tsl, theme = init_tsplot_theme(legend_col = 6))
```

For comparison, this easily fits, even though it has more characters:

```
tsl <- tstools::generate_random_ts(6, ts_names = c("a hello world","b hello world","c hello world","d hello world","e hello world","f hello world"))
tsplot(tsl, theme = init_tsplot_theme(legend_col = 6))
```

**Comment by HomoCodens** [comment]
Unfortunately, I don't think having individual widths for the legends is not possible without writing our own complete legend function. This is not currently on the map.

There is a `text.width` parameter. This only overwrites the default of "width of the longest label" though and does not allow to pass different widths either.

```
text.width

the width of the legend text in x ("user") coordinates. (Should be a single positive number even for a reversed x axis.) Defaults to the proper value computed by strwidth(legend).
```
