### ISSUE TITLE
Legend for CI should be customizable

### ISSUE THREAD

**Issue by omuelle** [mbannert/tstools#211]
When plotting for example interdecile ranges confidence interval is the wrong term.

**Comment by mbannert** [comment]
sorry, i don't get what you mean could you elaborate on this / provide an RR example if possible?

**Comment by omuelle** [comment]
What I plotted in the the bootstrap pdf is the interquantile range and the interdecile range, not confidence intervals, according to Klaus. So it should be possible to label it accordingly in the legend.

**Comment by mbannert** [comment]
Ah, thanks for the clarification. No even I got it. I agree, with should find a way to label arbitrarily. I thought about the same in a different context when I wanted to explicitly say `confidence interval` instead of CI because I always mixed it up with continous integration.

**Comment by HomoCodens** [comment]
Ah yes that should indeed be possible.
Something like this: 42bf7d88d1b9f1d548d343fd8347d07ff75fabf8

```R
ci <- list(
  "KOF Barometer" = list(
    "80" = list(
      lb = KOF$baro_lo_80,
      ub = KOF$baro_hi_80),
    "95" = list(
      lb = KOF$baro_lo_95,
      ub = KOF$baro_hi_95
    )))

tsplot(list("KOF Barometer" = KOF$baro_point_fc),
       ci = ci)
```

![rplot01](https://user-images.githubusercontent.com/32675029/43064761-65c7ed04-8e4f-11e8-83e2-644da78ac20b.png)


```R
tsplot(list("KOF Barometer" = KOF$baro_point_fc),
       ci = ci, theme = init_tsplot_theme(ci_legend_label = "the %ci_value%% ci interval for %series% is thusly"))
```

![rplot](https://user-images.githubusercontent.com/32675029/43064742-57eb3aec-8e4f-11e8-838b-6f16234f7b21.png)

**Comment by mbannert** [comment]
looks good to be, but let's test whether linebreaks `\n` work

**Comment by mbannert** [comment]
I think we can proceed here. Can you test the above and start a PR here?

**Comment by HomoCodens** [comment]
I've asked @omuelle for to test is as well.
If he agrees that this covers his needs we can proceed.

**Comment by omuelle** [comment]
Ah ok. Yes, looks good to me.
