### ISSUE TITLE
tsplots with only tsr don't work

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#213]
```R
> tstools::tsplot(tsr = tstools::generate_random_ts(1))
Error in names(tsl) <- paste0("series_", 1:length(tsl)) : 
  attempt to set an attribute on NULL
```
also
```R
> tstools::tsplot(NULL, tsr = tstools::generate_random_ts(1))
Error in UseMethod("tsplot") : 
  no applicable method for 'tsplot' applied to an object of class "NULL"
```

Much of `tsplot` just assumes the presence of `tsl`.

1) Just ignore this as it's improper use of the function?
2) Make it give a warning/more informative error in these cases?
3) Set tsl to an invisible series (only `NA`s, no legend?) and warn?

**Comment by mbannert** [comment]
I don't think we need and tsr only version. I do see the use case you describe /w the shiny package, but feel like this should be solved on shiny level. Maybe 3.) would be an option, too.
