### ISSUE TITLE
Area charts

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#217]
Something like this should work:

```
for(i in seq(length(tslist))) {
  if(i == 1) {
    lower_bound = 0
  } else {
    lower_bound = lower_bound + tslist[[i-1]]
  }

  upper_bound = lower_bound + tslist[[i]]

 draw polygon between lower bound and upper bound
}
```

Would look ugly with series with different start/end points though.

**Comment by HomoCodens** [comment]
Add left_as_band option

TODO:
- Handle series of different lengths properly
- NAs?
- Warning about zero-crossings?
- legend style?
- show_points?

```R
tsplot.list(generate_random_ts(3, ranges_min = 2, ranges_max = 5), left_as_band = TRUE)
```
![rplot02](https://user-images.githubusercontent.com/32675029/44140296-2e5dc560-a069-11e8-86cb-83f53f5acda7.png)

See b70e1e2a036c1fce324ae2e5f79e42d0afd49ccc. 
Far from done though.

**Comment by mbannert** [comment]
@HomoCodens. Yep, let's go for it. 
Btw. look pretty decent already. The only thing I find a little odd is the left and right 'margins' at the beginning and end of the series. But maybe I just need to get used to it.

**Comment by HomoCodens** [comment]
That's just the `line_to_middle` theme parameter being much more pronounced with the bands.
