### ISSUE TITLE
tsr does not handle NAs very well

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#219]
tsplot crashes when tsr series contains `NA`s. The problem is likely in the line that defines the range 
`tsr_r`. The `na.omit` argument of the range defaults to `FALSE` leaving us with NA NA for tsr_r which causes trouble later on.

**Comment by HomoCodens** [comment]
Yep, well spotted!

```R
tsplot(generate_random_ts(2), tsr = generate_random_ts(2, seed = 666, random_NAs = TRUE, random_NA_proportions = 0.2))
```

![rplot03](https://user-images.githubusercontent.com/32675029/44140615-2180df02-a06a-11e8-82a5-b66138a45aa8.png)
