### ISSUE TITLE
introduce relative stacked bar charts. 

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#27]
At some point plots that max at 100 % would be nice.

**Comment by HomoCodens** [comment]
Issue necromancy!
:ghost:

Should this work only with `group_bar_chart = TRUE` or also for stacked bar charts?
I assume the right axis is to be left alone in either case?

```R
library(tstools)

tsb1 <- ts(runif(30,0,abs(runif(1, 0, 50))),start=c(2010,1),frequency = 4)
tsb2 <- ts(runif(30,0,abs(runif(1, 0, 80))),start=c(2010,1),frequency = 4)

tt <- init_tsplot_theme()

tsplot(tsb1, tsb2, theme = tt, left_as_bar = TRUE, group_bar_chart = TRUE, relative_bar_chart = TRUE)
```

![normalized](https://user-images.githubusercontent.com/32675029/38028671-268b1a9e-3283-11e8-992f-42bd97cef64f.png)

**Comment by mbannert** [comment]
the resurrector strikes again... Honestly I never really thought about the group bar thing, because this came up before the group bar was even introduced. I could live with having to set `group_bar_chart` in order to use relative bars. Also it doesn't make much sense without the thought of grouping. As long as this works also for a single time series. I think we're good to go here. 

And yes, right axis should be left alone, if there is one. 
and ah, nice job indeed! :100:

**Comment by HomoCodens** [comment]
It should be possible to do with stacked bars too (such that the tallest stack has height 1) but I wasn't sure what kind of information that is going to convey.

Single series works too of course:
![singlenorm](https://user-images.githubusercontent.com/32675029/38029925-b2e269b8-3286-11e8-842d-066e5175fec1.png)

Feeling a bit tinkerish today so I'm tackling old and/or obscure issues. ;)

**Comment by HomoCodens** [comment]
For what it's worth.

![normd](https://user-images.githubusercontent.com/32675029/38030568-802e3f54-3288-11e8-9322-4bef51592c97.png)
![unnormd](https://user-images.githubusercontent.com/32675029/38030575-8209656a-3288-11e8-84c4-43d8864d6b6f.png)
