### ISSUE TITLE
read_swissdata_meta cannot deal with missing dim.order in yaml

### ISSUE THREAD

**Issue by omuelle** [mbannert/tstools#288]
For example:
`tstools::read_swissdata_meta("wd/ch.fso.besta.sex/ch.fso.besta.sex.yaml")`

**Comment by HomoCodens** [comment]
We could:

1) Decide `dim.order` is a required field and this is a swissdata issue.
2) Use the dimensions in the order they appear if it is missing

I tend towards 1).

**Comment by HomoCodens** [comment]
closing since I think you were using some old .yaml files anyway.
