### ISSUE TITLE
eliminate dead code

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#31]
old functions, particularly uncalled utils.

**Comment by HomoCodens** [comment]
I checked for R files defining functions that are not used anywhere in the package and that look like they might not be needed otherwise either.
Do we still need
* df_to_reg_ts
* m_to_q
* dateFromTs
* start_after_internal_nas
?

**Comment by mbannert** [comment]
these functions are standalone tools in themselves, other use cases and packages use them. 
df_to_reg_ts creates time series objects from data.frame with date indices, m_to_q does a KOF style aggregation of monthly to quarterly data and start_after_internal_nas selects the point in time after the last internal NA of series. dateFromTs, might be the only one but sounds useful to me in general. 

=> I would not scorch these functions for now.

**Comment by HomoCodens** [comment]
In that case #54
