### ISSUE TITLE
Round digits doesn't work

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#46]
```
library(kofdata)
library(tstools)


b <- get_time_series("kofbarometer")
writeTimeSeries(b,round_digits = 2)



```

**Comment by HomoCodens** [comment]
Looks like that param doesn't do anything at the moment.
Question: Do we also want to round for RData exports?

**Comment by mbannert** [comment]
I think we should enable rounding for all exports. Yet, rounding_digits = NULL should be possible, too. 
Not sure about the default, tho. Maybe NULL should really be the default.
