### ISSUE TITLE
fillUpYearWithNAs crashes for non-ts objects

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#48]
```
library(tstools)

tsb1 <- ts(runif(30,-30,20),start=c(2010,1),frequency = 4)
tsb2 <- ts(runif(30,0,50),start=c(2010,1),frequency = 4)
tsb3 <- ts(runif(30,0,50),start=c(2010,1),frequency = 4)

tsplot(tsb1,tsb2,tsb3,left_as_bar = T,auto_legend=F)
```

```
zoob1 <- as.zoo(tsb1)
zoob2 <- as.zoo(tsb2)
zoob3 <- as.zoo(tsb3)

tsplot(list(zoob1, zoob2, zoob3), left_as_bar = T, auto_legend = F)
```

```
 Error in `-.yearqtr`(frq, end(x)[2]) : 
  Can only subtract from yearqtr objects 
```

**Comment by HomoCodens** [comment]
The problem is that start and end return a vector for ts objects (e.g. `c(2017, 2)`) while zoo and xts objects use a single number (`2017.25`).
fillUpYearWithNAs needs to take this into account.

**Comment by mbannert** [comment]
What are we passing to fillupYearWithNAs? If its the time series object itself we can simply handle this with an s3method for all of these xts, zoo, ts.

**Comment by mbannert** [comment]
@HomoCodens introduced methods for *fillupYearWithNAs* now. Even tho we don't have finished methods for xts and zoo yet. The function should not crash anymore. I think the ts.union issue needs to be a separate issue. 

Just to make sure, I get this right... ts.union's been there for while and has not been introduced lately? 
I think we depend on time series to be regular (see drawTsLines which uses frequency) anyway. Shouldn't be too tricky to create a converter. One possible solution would be 
to create a *time_series_union.ts*, *time_series_union.zoo* method, *time_series_union.xts* method. Just need to figure out how to apply in do.call then.

**Comment by HomoCodens** [comment]
No, ts.union has been introduced with the autoranging for left_as_bar. See #49.
It looks like a lot of parts of tsplot do not support the different formats yet.

e.g. after fixing fillYearsWithNAs yesterday I came upon
```
Error in UseMethod("drawTsBars") : 
  no applicable method for 'drawTsBars' applied to an object of class "c('zooreg', 'zoo')"
```
