### ISSUE TITLE
Deprecate old function names

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#53]
1) Decide whether we want to do that
2) Figure out how

Currently some function names are camelCased and some are snake_cased. There should be consistency either way.

**Comment by mbannert** [comment]
I think we should do it. Your argument of better now than later is actually the most important one, given that we intent to increase the size of the target group. I suggest to do it as follows: 

1.  fix all other issues
2. feature freeze
3. create a separate branch and discuss which of the following approaches we should follow:

https://stackoverflow.com/questions/10099128/are-there-best-recommended-practices-to-follow-when-renaming-functions-in-a-new

**Comment by mbannert** [comment]
@HomoCodens I guess we're done. Let's start the renaming discussion. Here's what I suggest. 

1. add another branch 'aliases' 
2. rename a single function
3. add a file called aliases that will later contain all aliases for all functions (maybe split it up in 2-3 files)
4. try out deprecated suggestion from SO. 
5. delete and recreate NAMESPACE and documentation. 
6. proceed with the rest of the functions, if it worked. 

=> Main question: Which way of handling deprecation is the most appealing to you: 
I think we need to choose between Russell Pierce' and Brian Diggs' answer...
I still don't get what the benefit of Russell's idea is.

**Comment by mbannert** [comment]
Ok, I read the post again, more thoroughly and I am totally sold on Russell's approach.
Especially that `...` solution sounds appealing to me. Also it clearly shows users looking at the index which the preferred version is...

**Comment by HomoCodens** [comment]
Starting to look into it.
In `library(help="tstools")` I find the following functions that need renaming:
*computeDecimalTime
*concatTs
*fillUpYearWithNAs
*importTimeSeries
*initDefaultTheme
*overlapSortedLists
*overlapTslByName
*resolveOverlap
*stripLeadingNAsFromTs
*tsqm ?
*writeTimeSeries

**Comment by mbannert** [comment]
agreed w.r.t the internal functions.

**Comment by HomoCodens** [comment]
Check out https://github.com/mbannert/tstools/tree/aliases

**Comment by mbannert** [comment]
rockstar 👍 . I like the renaming, also the fact that there's some reasonable shortening as opposed to just replacing caMels with s_n_a_k_e_s. Only thing that needs to be fixed is the vignette. Not much work tho, cause it's mostly `tsplot` calls, but also `initDefaultTheme` and `writeTimeSeries` of old.

**Comment by HomoCodens** [comment]
I got a "Could not find `initDefaultTheme`" error when trying to run a kofreport. Fixed it by using the new name but we need to test if the exports of the aliases work.

**Comment by HomoCodens** [comment]
That feeling when typing up a issue/comment takes longer than the actual fix...
d5c079f26c2aa53fad34809597668f7eb08a184c
