### ISSUE TITLE
Bug when trying to find matching horizontal grids... 

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#60]
Though it works well for many cases, the functions that looks for matching horizontal grids fails in some occasion. Here's a reproducible example:

```
set.seed(123)
tsl <- ts(runif(10,4000,10000), start=c(2015,4),frequency = 4)
tsr <- ts(runif(10,6,28), start=c(2015,4),frequency = 4)
tsplot(tsl,tsr = tsr)
```

![image](https://user-images.githubusercontent.com/1382079/35647265-4230d252-06d2-11e8-8a3c-6eb61af61f16.png)

**Comment by HomoCodens** [comment]
See GH-61

![rplot](https://user-images.githubusercontent.com/32675029/35671557-16df14c8-073c-11e8-88e7-4a2c21134951.png)

**Comment by mbannert** [comment]
good job! love it.
