### ISSUE TITLE
Error in diff(left_ticks) : object 'left_ticks' not found

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#66]
It seems like setting `tt$y_grid_count_strict <- F` and using manual value ticks leads to the above error. Looks like we need to test manual_value_ticks (which is admittedly used seldom, with newly introduced magic) more thoroughly. I'll try to come up with a REX asap.

**Comment by HomoCodens** [comment]
403a3ba64a646048418e2e8d4b78c846d348e6c8

The variables left_ticks and right_ticks are used to check the range later in the function.
They are now also assigned when manual ticks are provided.
