### ISSUE TITLE
tt$y_grid_count_strict <- F as default?

### ISSUE THREAD

**Issue by mbannert** [mbannert/tstools#67]
Sometimes lines get cut off when choosing grids automatically. It seems solved when the above is it. Doesn't this mean it should be the default?

**Comment by mbannert** [comment]
done for now. @HomoCodens do you agree /w this? Close it for now.

**Comment by HomoCodens** [comment]
One could argue either way. For "pretty out of the box" plots `FALSE` probably is the better default.

Do you have an example of a case where this happened?
