### ISSUE TITLE
Leave out series in tsplot legend

### ISSUE THREAD

**Issue by dude233** [mbannert/tstools#69]
Some tsplot applications may require that two different series only have one legend entry, e.g. the interest rate target zone of central banks. At the moment, it is necessary to have two legend entries (e.g. floor target rate, cap target rate)

**Comment by mbannert** [comment]
@dude233 is this still a feature request? Can you provide us with a reproducible example?

**Comment by dude233** [comment]
Hallo Matthias!
Ja, das ist z.B. für die KOF Analysen, wenn nur eine Reihe angezeigt wird und darum keine Legende nötig ist (der Titel trägt diese Info bereits). Im Moment kann man, sofern ich mich richtig erinnere, nur auto_legend = F einstellen, was dann aber auch die Titel und Untertitel löscht. Ein "reproducible Example" ist daher theoretisch jede Grafik. Bin morgen wieder an der KOF!
Liebe Gruess
Marc
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 06/03/2018 - 16:58 (GMT)
An : tstools@noreply.github.com
Cc : marc.anderes@bluewin.ch, mention@noreply.github.com
Betreff : Re: [mbannert/tstools] Leave out series in tsplot legend (#69)
@dude233 is this still a feature request? Can you provide us with a reproducible example?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mbannert/tstools","title":"mbannert/tstools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mbannert/tstools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mbannert in #69: @dude233 is this still a feature request? Can you provide us with a reproducible example? "}],"action":{"name":"View Issue","url":"https://github.com/mbannert/tstools/issues/69#issuecomment-370829804"}}}

**Comment by mbannert** [comment]
@dude233 ok, I think this is fixed now. Title should not disappear anymore when auto_legend = F. Setting auto_legend to FALSE is definitely the way to go here. The other thing is a bug which is fixed now on dev. Currently we're running some tests to make sure everything works and will deploy all the new features and bug fixes on Monday.
