### ISSUE TITLE
NA kills stacks in tsplot(left_as_bar = T)

### ISSUE THREAD

**Issue by jburkhardt** [mbannert/tstools#84]
If there is a NA in one timeseries, the data stack in the plot of other timeseries are not displayed.
Example to produce the issue:
```R
# create time series
set.seed(123)
tsb1 <- ts(runif(30,-30,20),start=c(2010,3),frequency = 4)
tsb2 <- ts(runif(30,0,30),start=c(2010,1),frequency = 4)
tsb3 <- ts(runif(30,0,30),start=c(2012,1),frequency = 4)
# everthing is just fine
tsplot("ts1" = tsb1,
       "ts2" = tsb2,
       "ts3" = tsb3,
       left_as_bar = T,
       manual_value_ticks_l = seq(-60, 60, by = 10))
# create NA in tsb1 Qtr3 2013
tsb1[[13]] <- NA
# plot again
# issue: all data in Qtr3 2013 vanish in plot
tsplot("ts1" = tsb1,
       "ts2" = tsb2,
       "ts3" = tsb3,
       left_as_bar = T,
       manual_value_ticks_l = seq(-60, 60, by = 10))
```

**Comment by mbannert** [comment]
Hmm, seems pretty obvious as we cant add NAs up. Should NA = 0 in this case? If we decide to do that we need to make extra double sure it only happens stacked bar charts...

**Comment by jburkhardt** [comment]
With tsplot(left_as_bar = F) the issue does not appear. Maybe you can change NA to 0 here:
https://github.com/mbannert/tstools/blob/master/R/df_to_reg_ts.R#L68
Or add an option in df_to_reg_ts(NA_as_zero)

**Comment by mbannert** [comment]
@jburkhardt, again looks like you have an outdated version. If I run this, 2013 Q3 looks like it's supposed to:
![image](https://user-images.githubusercontent.com/1382079/36780358-106139fe-1c73-11e8-836a-5ee28a1a78fb.png)

Basically NA is like that part of the series is 0.

**Comment by jburkhardt** [comment]
Thanks! Same as https://github.com/mbannert/tstools/issues/85
