### ISSUE TITLE
different length of ts leads to incomplete plot with tsplot(left_as_bar = T)

### ISSUE THREAD

**Issue by jburkhardt** [mbannert/tstools#85]
If you ```tsplot``` multiple time series that have different lengths, the setting ```left_as_bar = T``` leads to incomplete plotting.
```R
# create time series
set.seed(123)
tsb1 <- ts(runif(30,-30,20),start=c(2010,3),frequency = 4) # end Qrt4 2017
tsb2 <- ts(runif(30,0,30),start=c(2010,1),frequency = 4) # ends Qrt2 2017
tsb3 <- ts(runif(30,0,30),start=c(2012,1),frequency = 4) # ends Qrt2 2019
# add to list
datalist <- list()
datalist$tsb1 <- tsb1
datalist$tsb2 <- tsb2
datalist$tsb3 <- tsb3
# plot as lines - everything is fine: all data in plot
tsplot(datalist,
       left_as_bar = F,
       manual_value_ticks_l = seq(-60, 60, by = 5))
# plot as bar - data in plot are incomplete
tsplot(datalist,
       left_as_bar = T,
       manual_value_ticks_l = seq(-60, 60, by = 5))
```
Line Chart with all data:
![bildschirmfoto 2018-02-27 um 10 50 12](https://user-images.githubusercontent.com/5146122/36721740-11955e6c-1bac-11e8-9d47-7aa604744204.png)
Bar Chart missing data as soon as there is only one time series. See beginning and end of chart.
![bildschirmfoto 2018-02-27 um 10 50 26](https://user-images.githubusercontent.com/5146122/36721774-2e513e72-1bac-11e8-83fc-4223160c7721.png)

**Comment by HomoCodens** [comment]
I believe this was fixed in #44.
I get the following plot with the code above:
![rplot](https://user-images.githubusercontent.com/32675029/36739059-f296356a-1bd6-11e8-97ef-5a345066d102.png)

**Comment by mbannert** [comment]
@jburkhardt can download from github and check whether it's fixed. I also think it should be fixed in the CRAN version. I can confirm, if I run it, it looks like what @HomoCodens posted.

**Comment by jburkhardt** [comment]
@mbannert @HomoCodens Thank you! After a package reinstallation from Github it works for me as well. Sorry for the inconvenience!
