### ISSUE TITLE
Legends with two axes

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#90]
Opening this as a sort of brainstorming think tank on how to handle these.

One option would be to right-align the legend for the right series and apply legend_col to both "sub legends". Legends could not be wider than half the width of the plot but that's up to the user.

**Comment by HomoCodens** [comment]
Disentangling the legends in such a way would also eliminate issues such as #88:
```
      legend("bottomleft",
             legend = tsln,
             ncol = theme$legend_col,
             bty = "n",
             border = NA,
             fill = theme$bar_fill_color[1:length(tsln)],
             x.intersp = theme$legend_intersp_x,
             y.intersp = theme$legend_intersp_y)
      legend("bottomright",
             legend = tsrn,
             bty = "n",
             border = NA,
             ncol = theme$legend_col,
             lty = theme$lty[1:length(tsrn)],
             lwd = theme$lwd[1:length(tsrn)],
             col = theme$line_colors[1:length(tsrn)])
```
![rplot01](https://user-images.githubusercontent.com/32675029/36964013-3a249d52-204d-11e8-9c5c-0af4ca55d693.png)

**Comment by mbannert** [comment]
This awesome to me! I do not see why this could be bad (yet). Let's go!

**Comment by mbannert** [comment]
PR #92 fixes this.
