### ISSUE TITLE
Possible mismatching of line type between plot and legend

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/tstools#94]
Looks like the line types of tsr are "advanced" by the length of tsl even if those are bars.
Either this must be changed or add_legend needs to take it into account also.
```  
    total_le <- length(tsl) + length(tsr)
    start_r <- (total_le - (length(tsr)-1)):total_le
    
    
    tt_r <- theme
    tt_r$line_colors <- tt_r$line_colors[start_r]
    if(!all(is.na(tt_r$lwd[start_r]))) tt_r$lwd <- na.omit(tt_r$lwd[start_r])
    if(!all(is.na(tt_r$lwd[start_r]))) tt_r$lty <- na.omit(tt_r$lty[start_r])
    
    draw_ts_lines(tsr,theme = tt_r)
```

**Comment by HomoCodens** [comment]
Test case:
```
library(tstools)

# Create list of two time series
tslist <- list(ts(runif(100), start = 1990, frequency = 4),
                       ts(runif(100), start = 1990, frequency = 4),
                       ts(runif(100), start = 1990, frequency = 4))

tsplot(tslist[1:2], tsr = tslist_unnamed[[3]],
       theme = init_tsplot_theme(lty = c(1, 2, 3, 4), line_colors = c("#FF0000", "#00FF00", "#0000BB")), left_as_bar = TRUE)
```

Question: If the left series are bars, should the right start using line specs at index `1` (`lty == 1` and `color == "#FF0000"` on the example above) or `length(tsl) + 1` (`lty == 3` and `color == "#0000BB"`)?
Is there a CC rule about the colours for example?

**Comment by mbannert** [comment]
change line color default first and last value. don't leave out first 2 in this example if left_as_bar = T
